module Dorks
   class Dork4429 < Vulpes::Dork

      def initialize
         super({
            name: "Dork 4429",
            ghdb_url: "https://www.exploit-db.com/ghdb/4429",
            severity: "2",
            category: "files_containing_juicy_info",
            publish_date: "2017-04-12",
            author: "anonymous",
            dork: <<~EDORK,
"# This file was generated by libcurl! Edit at your own risk." ext:txt
EDORK
            description: <<~EDESC
Finds leftover cookie data, sometimes containing vulnerable information (often encrypted) Dxtroyer
EDESC
         })

      end
   end
end
