module Dorks
   class Dork6175 < Vulpes::Dork

      def initialize
         super({
            name: "Dork 6175",
            ghdb_url: "https://www.exploit-db.com/ghdb/6175",
            severity: "3",
            category: "pages_containing_login_portals",
            publish_date: "2020-06-04",
            author: "Vikash Kumar",
            dork: <<~EDORK,
inurl:admin/login.aspx
EDORK
            description: <<~EDESC
# Results: List of Admin Login Webpage generated by web servers
# running the Microsoft ASP.NET framework.
# Date: 2020-05-31
# Linkedin: https://www.linkedin.com/in/vikash-kumar-7b938a176
# Twitter: https://twitter.com/vksutk
--
Thanks & Regards
*Vikash Kumar*
EDESC
         })

      end
   end
end
