module Dorks
   class Dork1212 < Vulpes::Dork

      def initialize
         super({
            name: "Dork 1212",
            ghdb_url: "https://www.exploit-db.com/ghdb/1212",
            severity: "4",
            category: "files_containing_passwords.proftpd",
            publish_date: "2005-11-30",
            author: "anonymous",
            dork: <<~EDORK,
"parent directory" +proftpdpasswd
EDORK
            description: <<~EDESC
User names and password hashes from web server backups generated by cpanel for ProFTPd. Password hashes can be cracked, granting direct access to FTP accounts. Unix passwd and shadow files can sometimes be found with this query as well.
EDESC
         })

      end
   end
end
