module Dorks
   class Dork665 < Vulpes::Dork

      def initialize
         super({
            name: "Dork 665",
            ghdb_url: "https://www.exploit-db.com/ghdb/665",
            severity: "4",
            category: "network_or_vulnerability_data",
            publish_date: "2004-11-12",
            author: "anonymous",
            dork: <<~EDORK,
intitle:"sysinfo * " intext:"Generated by Sysinfo * written by The Gamblers."
EDORK
            description: <<~EDESC
intitle:"sysinfo * " intext:"Generated by Sysinfo * written by The Gamblers."
Lots of information leakage on these pages about active network services, server info, network connections, etc..
EDESC
         })

      end
   end
end
