module Dorks
   class Dork42 < Vulpes::Dork

      def initialize
         super({
            name: "Dork 42",
            ghdb_url: "https://www.exploit-db.com/ghdb/42",
            severity: "2",
            category: "files_containing_juicy_info",
            publish_date: "2003-06-30",
            author: "anonymous",
            dork: <<~EDORK,
"generated by wwwstat"
EDORK
            description: <<~EDESC
More www statistics on the web. This one is very nice.. Lots of directory info, and client access statistics, email addresses.. lots os good stuff.You know, these are SOOO dangerous, especially if INTRANET users get logged... talk about mapping out an intranet quickly...thanks, sac =)
EDESC
         })

      end
   end
end
