module Dorks
   class Dork3086 < Vulpes::Dork

      def initialize
         super({
            name: "Dork 3086",
            ghdb_url: "https://www.exploit-db.com/ghdb/3086",
            severity: "6",
            category: "advisories_and_vulnerabilities.cve-2006-5292",
            publish_date: "2010-11-15",
            author: "anonymous",
            dork: <<~EDORK,
"generated by Exhibit Engine 1.5 RC 4"
EDORK
            description: <<~EDESC
Exhibit Engine 1.5 RC 4 (photo_comment.php) File Include - CVE: 2006-5292: https://www.exploit-db.com/exploits/2509
EDESC
         })

      end
   end
end
