module Dorks
   class Dork4675 < Vulpes::Dork

      def initialize
         super({
            name: "Dork 4675",
            ghdb_url: "https://www.exploit-db.com/ghdb/4675",
            severity: "7",
            category: "network_or_vulnerability_data.acunetix",
            publish_date: "2018-02-19",
            author: "ManhNho",
            dork: <<~EDORK,
intitle: "Generated by Acunetix WVS Reporter"
EDORK
            description: <<~EDESC
Finds reports left behind by Acunetix (vulnerability scanner)
ManhNho
EDESC
         })

      end
   end
end
