module Dorks
   class Dork577 < Vulpes::Dork

      def initialize
         super({
            name: "Dork 577",
            ghdb_url: "https://www.exploit-db.com/ghdb/577",
            severity: "5",
            category: "advisories_and_vulnerabilities.plesk-server",
            publish_date: "2004-10-16",
            author: "anonymous",
            dork: <<~EDORK,
"This page has been automatically generated by Plesk Server Administrator"
EDORK
            description: <<~EDESC
Plesk Server Administrator (PSA) is web based software that enables remote administration of web servers. It can be used on Linux and other systems that support PHP. Due to an input validation error in Plesk Server Administrator, it is possible for a remote attacker to make a specially crafted web request which will display PHP source code. This is acheivable by connecting to a host (using the IP address rather than the domain name), and submitting a request for a known PHP file along with a valid username. http://www.securityfocus.com/bid/3737
EDESC
         })

      end
   end
end
