module Dorks
   class Dork1177 < Vulpes::Dork

      def initialize
         super({
            name: "Dork 1177",
            ghdb_url: "https://www.exploit-db.com/ghdb/1177",
            severity: "3",
            category: "sensitive_directories",
            publish_date: "2005-11-11",
            author: "anonymous",
            dork: <<~EDORK,
log inurl:linklint filetype:txt -"checking"
EDORK
            description: <<~EDESC
Linklint is an Open Source Perl program that checks links on web sites. This search finds the Linklint log directory. Complete site map able to be recreated, and if you go back one directory you can see all the other files generated by linklint. Thanks to CP for direction.
EDESC
         })

      end
   end
end
