module Dorks
   class Dork102 < Vulpes::Dork

      def initialize
         super({
            name: "Dork 102",
            ghdb_url: "https://www.exploit-db.com/ghdb/102",
            severity: "4",
            category: "files_containing_juicy_info",
            publish_date: "2004-03-04",
            author: "anonymous",
            dork: <<~EDORK,
intitle:"wbem" compaq login "Compaq Information Technologies Group"
EDORK
            description: <<~EDESC
These devices are running HP Insight Management Agents for Servers which "provide device information for all managed subsystems. Alerts are generated by SNMP traps." The information on these pages include server addresses and other assorted SNMP information.
EDESC
         })

      end
   end
end
