module Dorks
   class Dork3941 < Vulpes::Dork

      def initialize
         super({
            name: "Dork 3941",
            ghdb_url: "https://www.exploit-db.com/ghdb/3941",
            severity: "7",
            category: "files_containing_juicy_info",
            publish_date: "2014-03-31",
            author: "anonymous",
            dork: <<~EDORK,
filetype:pdf "acunetix website audit" "alerts summary"
EDORK
            description: <<~EDESC
Finds reports generated by Acunetix scans. - Andy G - twitter.com/vxhex
EDESC
         })

      end
   end
end
