module Dorks
   class Dork6097 < Vulpes::Dork

      def initialize
         super({
            name: "Dork 6097",
            ghdb_url: "https://www.exploit-db.com/ghdb/6097",
            severity: "7",
            category: "network_or_vulnerability_data.skipfish",
            publish_date: "2020-05-19",
            author: "BillyV4",
            dork: <<~EDORK,
intitle:"Skipfish - scan results browser"
EDORK
            description: <<~EDESC
# Description: Find reports generated by Skipfish vulnerability scanner.
# Author: Carlos Ramírez L. (BillyV4)
EDESC
         })

      end
   end
end
