module Dorks
   class Dork95 < Vulpes::Dork

      def initialize
         super({
            name: "Dork 95",
            ghdb_url: "https://www.exploit-db.com/ghdb/95",
            severity: "3",
            category: "files_containing_juicy_info",
            publish_date: "2004-03-04",
            author: "anonymous",
            dork: <<~EDORK,
intitle:"Usage Statistics for" "Generated by Webalizer"
EDORK
            description: <<~EDESC
The webalizer program shows web statistics for web servers. This information includes who is visiting the site, what pages they visit, error codes produced, filetypes hosted on the server, number of hits, referrers, exit pages, and more which can provide very interesting recon information for an attacker.
EDESC
         })

      end
   end
end
