module Dorks
   class Dork4087 < Vulpes::Dork

      def initialize
         super({
            name: "Dork 4087",
            ghdb_url: "https://www.exploit-db.com/ghdb/4087",
            severity: "5",
            category: "various_online_devices",
            publish_date: "2015-10-05",
            author: "anonymous",
            dork: <<~EDORK,
intitle:Global Traffic Statistics "Ntop"
EDORK
            description: <<~EDESC
Google dork Description: View Global Traffic Statistics Google search: intitle:Global Traffic Statistics "Ntop" Submited: 2015-10-3 Note: Ntop shows the current network usage. It displays a list of hosts that are currently using the network and reports information concerning the IP (Internet Protocol) traffic generated by each host.
EDESC
         })

      end
   end
end
