module Dorks
   class Dork6098 < Vulpes::Dork

      def initialize
         super({
            name: "Dork 6098",
            ghdb_url: "https://www.exploit-db.com/ghdb/6098",
            severity: "7",
            category: "network_or_vulnerability_data",
            publish_date: "2020-05-19",
            author: "BillyV4",
            dork: <<~EDORK,
-site:"pentest-tools.com" intext:"Scan coverage information" AND "List of tests" ext:PDF
EDORK
            description: <<~EDESC
# Google Dork: -site:"pentest-tools.com" intext:"Scan coverage information"
AND "List of tests" ext:PDF
# Description: Find reports generated by Pentest-Tools.com vulnerability
scanner.
# Author: Carlos Ramírez L. (BillyV4)
EDESC
         })

      end
   end
end
