module Dorks
   class Dork1157 < Vulpes::Dork

      def initialize
         super({
            name: "Dork 1157",
            ghdb_url: "https://www.exploit-db.com/ghdb/1157",
            severity: "6",
            category: "advisories_and_vulnerabilities.sqli.utopia-news-pro",
            publish_date: "2005-10-06",
            author: "anonymous",
            dork: <<~EDORK,
"News generated by Utopia News Pro" | "Powered By: Utopia News Pro"
EDORK
            description: <<~EDESC
Utopia News Pro 1.1.3 (and prior versions) SQL Injection & XSSadvisory & poc exploit:http://rgod.altervista.org/utopia113.html
EDESC
         })

      end
   end
end
