module Dorks
   class Dork4449 < Vulpes::Dork

      def initialize
         super({
            name: "Dork 4449",
            ghdb_url: "https://www.exploit-db.com/ghdb/4449",
            severity: "4",
            category: "files_containing_juicy_info",
            publish_date: "2017-04-28",
            author: "anonymous",
            dork: <<~EDORK,
"[PHPSESSID]" ext:log
EDORK
            description: <<~EDESC
Looks for logs with session ID's generated by PHP Dxtroyer
EDESC
         })

      end
   end
end
