module Dorks
   class Dork305 < Vulpes::Dork

      def initialize
         super({
            name: "Dork 305",
            ghdb_url: "https://www.exploit-db.com/ghdb/305",
            severity: "2",
            category: "files_containing_juicy_info",
            publish_date: "2004-07-06",
            author: "anonymous",
            dork: <<~EDORK,
Welcome to ntop!
EDORK
            description: <<~EDESC
Ntop shows the current network usage. It displays a list of hosts that are currently using the network and reports information concerning the IP (Internet Protocol) traffic generated by each host. An attacker may use this to gather information about hosts and services behind the firewall.
EDESC
         })

      end
   end
end
