module Dorks
   class Dork4820 < Vulpes::Dork

      def initialize
         super({
            name: "Dork 4820",
            ghdb_url: "https://www.exploit-db.com/ghdb/4820",
            severity: "6",
            category: "network_or_vulnerability_data.munin",
            publish_date: "2018-05-16",
            author: "Sang Bui",
            dork: <<~EDORK,
inurl:/munin/localdomain/localhost.localdomain/open_files.html
EDORK
            description: <<~EDESC
Search for the page that generated by Munin, this page will contains the
sensitive information on the systems & application.
EDESC
         })

      end
   end
end
