module Dorks
   class Dork398 < Vulpes::Dork

      def initialize
         super({
            name: "Dork 398",
            ghdb_url: "https://www.exploit-db.com/ghdb/398",
            severity: "3",
            category: "files_containing_juicy_info",
            publish_date: "2004-08-02",
            author: "anonymous",
            dork: <<~EDORK,
"allow_call_time_pass_reference" "PATH_INFO"
EDORK
            description: <<~EDESC
Returns publically visible pages generated by the php function phpinfo(). This search differs from other phpinfo() searches in that it doesn't depend on the filename being called "phpinfo.php". Some result files that include phpinfo are:
EDESC
         })

      end
   end
end
