module Dorks
   class Dork4162 < Vulpes::Dork

      def initialize
         super({
            name: "Dork 4162",
            ghdb_url: "https://www.exploit-db.com/ghdb/4162",
            severity: "3",
            category: "files_containing_juicy_info",
            publish_date: "2015-12-21",
            author: "anonymous",
            dork: <<~EDORK,
"Stats generated by pisg v0.73"
EDORK
            description: <<~EDESC
Dork with Stats for irc channels. Discovered by Rootkit Pentester.
EDESC
         })

      end
   end
end
