module Dorks
   class Dork750 < Vulpes::Dork

      def initialize
         super({
            name: "Dork 750",
            ghdb_url: "https://www.exploit-db.com/ghdb/750",
            severity: "3",
            category: "files_containing_juicy_info",
            publish_date: "2004-12-05",
            author: "anonymous",
            dork: <<~EDORK,
"Generated by phpSystem"
EDORK
            description: <<~EDESC
PhpSystem shows info about unix systems, including: General Info (kernel, cpu, uptime), Connections, Who Is Logged In, Memory, Swap and active mounts.
EDESC
         })

      end
   end
end
