module Dorks
   class Dork4676 < Vulpes::Dork

      def initialize
         super({
            name: "Dork 4676",
            ghdb_url: "https://www.exploit-db.com/ghdb/4676",
            severity: "7",
            category: "network_or_vulnerability_data.burp",
            publish_date: "2018-02-20",
            author: "ManhNho",
            dork: <<~EDORK,
intitle:"Burp Scanner Report" | "Report generated by Burp Scanner"
EDORK
            description: <<~EDESC
Finds reports left behind by Burp Scanner (vulnerability scanner)
ManhNho
EDESC
         })

      end
   end
end
